name: 'Link Checker: All English'

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:

  permissions:
    contents: read
    pull-requests: read

  concurrency:
    group:'${{github.workflow}}@${{github.event.pull_request.head.label || github.head_ref || github.ref}}'
    cancel-in-progress: true

  jobs:
    check-links:
      runs-on: ${{fromJSON('["ubuntu-latest","self-hosted"]')[github.repository] == 'github/docs-internal'}}
  
